- name: myapb playbook to provision the application
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    eclipse_che_version: 6.7.1
    nexus_version: 3.12.1
    infrasvcs_adm_user: adminuser
    infrasvcs_adm_pwd: adminpwd
    github_account: openshift-labs
    github_ref: master
    user_count: 1
    user_format: "user%d"
    user_password: openshift

  roles:
  - role: ansible.kubernetes-modules
    install_python_requirements: no
  - role: ansibleplaybookbundle.asb-modules

  tasks:
  - import_role:
      name: common
    tags: always

  - import_role:
      name: openshift_istio
    vars:
      istio_version: 0.8.0
      openshift_master_public: "{{ openshift_master_url }}"
    tags: istio

  - import_role:
      name: openshift_sonatype_nexus
    vars:
      project_name: "{{ namespace }}"
      nexus_image_version: "{{ nexus_version }}"
      nexus_max_memory: 6Gi
      nexus_admin_user: "{{ infrasvcs_adm_user }}"
      nexus_admin_password: "{{ infrasvcs_adm_pwd }}"
    tags: nexus

  - import_role:
      name: openshift_gogs
    vars:
      project_name: "{{ namespace }}"
      gogs_route: "gogs-{{ namespace }}.{{ apps_hostname_suffix }}"
      gogs_image_version: 0.11.34
      gogs_admin_user: "{{ infrasvcs_adm_user }}"
      gogs_admin_password: "{{ infrasvcs_adm_pwd }}"
      gogs_password: "{{ user_password }}"
      gogs_deploy_retry_delay: 60
      gogs_deploy_retry_count: 30
      gogs_generate_user_count: "{{ user_count }}"
      gogs_generate_user_format: "{{ user_format }}"
      clean_deploy: true
    tags: gogs

  - import_role:
      name: openshift_workshopper
    vars:
      project_name: "{{ namespace }}"
      workshopper_content_url_prefix: "https://raw.githubusercontent.com/{{ github_account }}/rhsummit18-cloudnative-guides/{{ github_ref }}"
      workshopper_workshop_urls: "https://raw.githubusercontent.com/{{ github_account }}/rhsummit18-cloudnative-guides/{{ github_ref }}/_rhsummit18.yml"
      workshopper_env_vars:
        OPENSHIFT_MASTER_URL: "{{ openshift_master_url }}"
        APPS_HOSTNAME_SUFFIX: "{{ apps_hostname_suffix }}"
        GIT_HOSTNAME: "gogs-{{ namespace }}.{{ apps_hostname_suffix }}"
        ECLIPSE_CHE_URL: "http://che-{{ namespace }}.{{ apps_hostname_suffix }}"
        NEXUS_EXTERNAL_URL: "http://nexus-{{ namespace }}.{{ apps_hostname_suffix }}"
        GRAFANA_URL: "http://grafana-istio-system.{{ apps_hostname_suffix }}"
        JAEGER_URL: "https://jaeger-query-istio-system.{{ apps_hostname_suffix }}"
        PROMETHEUS_URL: "http://prometheus-istio-system.{{ apps_hostname_suffix }}"
    tags: guides

  - import_role:
      name: openshift_eclipse_che
    vars:
      project_name: "{{ namespace }}"
      che_version: "{{ eclipse_che_version }}"
      route_suffix: "{{ apps_hostname_suffix }}"
      multi_user: true
      che_generate_user_count: "{{ user_count }}"
      che_generate_user_format: "{{ user_format }}"
      che_generate_user_password: "{{ user_password }}"
      keycloak_admin_user: "{{ infrasvcs_adm_user }}"
      keycloak_admin_pwd: "{{ infrasvcs_adm_pwd }}"
      install_java_oc_stack: false
      install_custom_stacks_json: [ "{{ lookup('file', 'files/java-stack.json') }}" ]
    tags: eclipse-che

  - import_role:
      name: provision-cloudnative-istio-apb
    playbook_debug: false
    tags: workshop
