- src: siamaksade.openshift_sonatype_nexus
  version: ocp-3.9-1
  name: openshift_sonatype_nexus

- src: siamaksade.openshift_gogs
  version: ocp-3.9
  name: openshift_gogs

- src: siamaksade.openshift_workshopper
  version: ocp-3.9
  name: openshift_workshopper

- src: siamaksade.openshift_eclipse_che
  version: ocp-3.9-2
  name: openshift_eclipse_che

- src: siamaksade.openshift_istio
  version: ocp-3.9
  name: openshift_istio