---
- name: Deploy Infra Components for Cloud-Native Labs at Red Hat Summit 2018
  hosts: localhost
  gather_facts: false
  run_once: true
  vars:
    lab_infra_project: lab-infra
    user_gogs_admin: gogs
    user_gogs_user: developer
    user_gogs_password: openshift
    openshift_cli: oc

  tasks:
    - include_role:
        name: openshift_common_facts
      tags: always

    - name: create lab infra project
      shell: "{{ openshift_cli }} new-project {{ lab_infra_project }} --display-name='Lab Infra'"
      ignore_errors: true
      tags: always

    # deploy nexus
    - import_role:
        name: openshift_sonatype_nexus
      vars:
        project_name: "{{ lab_infra_project }}"
        nexus_image_version: 3.7.1
        nexus_max_memory: 6Gi
      tags: nexus

    # deploy gogs
    - set_fact:
        gogs_hostname: gogs-{{ lab_infra_project }}.{{ apps_hostname_suffix }}
      tags: always

    - import_role:
        name: openshift_gogs
      vars:
        project_name: "{{ lab_infra_project }}"
        gogs_route: "{{ gogs_hostname }}"
        gogs_image_version: 0.11.34
        gogs_admin_user: "{{ user_gogs_admin }}"
        gogs_admin_password: "{{ user_gogs_password }}"
        gogs_user: "{{ user_gogs_user }}"
        gogs_password: "{{ user_gogs_password }}"
        clean_deploy: true
      tags: gogs

    # deploy guides
    - import_role:
        name: openshift_workshopper
      vars:
        project_name: "{{ lab_infra_project }}"
        workshopper_content_url_prefix: "https://raw.githubusercontent.com/openshift-labs/rhsummit18-cloudnative-guides/master"
        workshopper_workshop_urls: "https://raw.githubusercontent.com/openshift-labs/rhsummit18-cloudnative-guides/master/_rhsummit18.yml"
        workshopper_env_vars:
          PROJECT_SUFFIX: ""
          GOGS_URL: http://{{ gogs_hostname }}
          OPENSHIFT_DOCS_BASE: "https://docs.openshift.com/container-platform/3.9"
      tags: guides

    # deploy eclipse che
    - import_role:
        name: openshift_eclipse_che
      vars:
        project_name: "{{ lab_infra_project }}"
        che_version: "6.3.0"
        route_suffix: "{{ apps_hostname_suffix }}"
      tags: eclipse-che

    - name: wait for eclipse che to be running
      uri:
        url: http://che-{{ lab_infra_project }}.{{ apps_hostname_suffix }}/api/
        status_code: 200
      register: result
      until: result.status == 200
      retries: "30"
      delay: "10"
      tags: eclipse-che

    - name: create custom stack for jdk and openshift cli
      uri:
        url: http://che-{{ lab_infra_project }}.{{ apps_hostname_suffix }}/api/stack
        method: POST
        body: |
          {
            "name": "Java RH Summit",
            "description": "Java JDK Stack on CentOS for Red Hat Summit 2018 Labs",
            "scope": "general",
            "workspaceConfig": {
              "environments": {
                "default": {
                  "recipe": {
                    "type": "dockerimage",
                    "content": "siamaksade/che_centos_jdk8:spring-boot-dep"
                  },
                  "machines": {
                    "dev-machine": {
                      "env": {},
                      "servers": {
                        "8080/tcp": {
                          "attributes": {},
                          "protocol": "http",
                          "port": "8080"
                        },
                        "8000/tcp": {
                          "attributes": {},
                          "protocol": "http",
                          "port": "8000"
                        }
                      },
                      "volumes": {},
                      "installers": [
                        "org.eclipse.che.exec",
                        "org.eclipse.che.terminal",
                        "org.eclipse.che.ws-agent"
                      ],
                      "attributes": {
                        "memoryLimitBytes": "2147483648"
                      }
                    }
                  }
                }
              },
              "commands": [
                {
                  "commandLine": "mvn clean install -f ${current.project.path} -s ${current.project.path}/.settings.xml",
                  "name": "build",
                  "type": "mvn",
                  "attributes": {
                    "goal": "Build",
                    "previewUrl": ""
                  }
                },
                {
                  "commandLine": "mvn spring-boot:run -f ${current.project.path} -s ${current.project.path}/.settings.xml",
                  "name": "run spring-boot",
                  "type": "mvn",
                  "attributes": {
                    "goal": "Run",
                    "previewUrl": "${server.8080/tcp}"
                  }
                }
              ],
              "projects": [],
              "defaultEnv": "default",
              "name": "default",
              "links": []
            },
            "components": [
              {
                "version": "---",
                "name": "CentOS"
              },
              {
                "version": "1.8.0_45",
                "name": "JDK"
              },
              {
                "version": "3.2.2",
                "name": "Maven"
              },
              {
                "version": "2.4",
                "name": "Ansible"
              },
              {
                "version": "3.9.14",
                "name": "OpenShift CLI"
              },
            ],
            "creator": "ide",
            "tags": [
              "Java",
              "JDK",
              "Maven",
              "Ansible",
              "CentOS",
              "Git"
            ],
            "id": "java-centos-rhsummit18"
          }
        body_format: json
        status_code: 200,201
      tags: eclipse-che

    
