- name: get auth token from keycloak master realm
  uri:
    url: http://keycloak-{{ namespace }}.{{ apps_hostname_suffix }}/auth/realms/master/protocol/openid-connect/token
    method: POST
    body: "username={{ infrasvcs_adm_user }}&password={{ infrasvcs_adm_pwd }}&grant_type=password&client_id=admin-cli"
    status_code: 200
    headers:
      Content-Type: "application/x-www-form-urlencoded"
  register: master_access_token_result

- name: get auth token from keycloak che realm
  uri:
    url: http://keycloak-{{ namespace }}.{{ apps_hostname_suffix }}/auth/realms/che/protocol/openid-connect/token
    method: POST
    body: "username=admin&password=admin&grant_type=password&client_id=admin-cli"
    status_code: 200
    headers:
      Content-Type: "application/x-www-form-urlencoded"
  register: che_access_token_result

- set_fact:
    master_access_token_bearer: "{{ master_access_token_result.json | json_query('access_token') }}"
    che_access_token_bearer: "{{ che_access_token_result.json | json_query('access_token') }}"

- name: create custom stack for jdk and openshift cli
  uri:
    url: http://che-{{ namespace }}.{{ apps_hostname_suffix }}/api/stack
    method: POST
    body: "{{ lookup('file','files/che-stack.json') }}"
    body_format: json
    status_code: 200,201
    headers:
      Authorization: "Bearer {{ che_access_token_bearer }}"
  register: stack_json

- set_fact:
    stack_id: "{{ stack_json.json|json_query('id') }}"

- name: give all users access to the stack
  uri:
    url: http://che-{{ namespace }}.{{ apps_hostname_suffix }}/api/permissions
    method: POST
    body: "{{ lookup('template','che-permissions.json.j2') }}"
    body_format: json
    status_code: 204
    headers:
      Authorization: "Bearer {{ che_access_token_bearer }}"
  vars:
    stack_id: "{{ stack_id }}"
